services:
  db:
    image: postgres:16
    container_name: itblog_db
    environment:
      POSTGRES_USER: itblog
      POSTGRES_PASSWORD: itblog
      POSTGRES_DB: itblog
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: